### ISSUE TITLE
Nginx deployment configuration issue

### ISSUE THREAD

**Issue by oscanog** [mhelmer/dockerize-uwsgi-nginx-webpack#6]
![issue](https://cloud.githubusercontent.com/assets/20588485/19224935/a4fa0608-8ec2-11e6-8115-ea760ef36e13.jpg)

**Comment by mhelmer** [comment]
Hi,

First thing, I noticed I forgot to map port 80 from the nginx container. So, I guess what you're seing is served by your host system.

Secondly I have not added a production config for webpack (minified, without source maps, production node env etc).

These settings never found it back here because I'll usually do production setup way later than dev. Anyway, I will fix those problems within a few days. Just beware the it is not secure to run it in production as it is, since it should run in HTTPS only.

**Comment by mhelmer** [comment]
I suppose you did the following?

``` bash
docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
```

**Comment by oscanog** [comment]
yep, I did.

**Comment by mhelmer** [comment]
This should be fixed now. Just make sure to add your ssl certs or set up letsencrypt by following the links in `README.md`. Also configure the django production settings with `ALLOWED_HOSTS` etc..
